### ISSUE TITLE
项目介绍中 BasicBitmap C++版本 性能不如 GDI 是这个意思吗 ?

### ISSUE THREAD

**Issue by sgf** [skywind3000/BasicBitmap#3]
被这个项目的介绍吸引 好像很厉害
但是看了项目介绍中 似乎
BasicBitmap C++版本 不透明 情况下比GDI略差 而透明情况下也和GDI相当或者略高于GDI 
好像 优势不是很明显？

**Comment by skywind3000** [comment]
我是在说明两个问题：
1. 没有经过 SIMD优化的 C++ 代码（BasicBitmap.cpp），性能并不低
2. 经过 SIMD 优化的 SSE / AVX 代码（BasicBitmap_SSE2.cpp）性能比 GDI / DirectDraw 高很多。

**Comment by sgf** [comment]
哦 哈哈 好的 感谢
