### ISSUE TITLE
为何不支持1bit 或4bit bmp

### ISSUE THREAD

**Issue by imkos** [skywind3000/BasicBitmap#4]

**Comment by skywind3000** [comment]
1. 用的太少
2. 为了支持额外增加的臃肿代码太多

特殊需求可以使用我 [pixellib](https://github.com/skywind3000/pixellib) 中的：

https://github.com/skywind3000/pixellib/blob/master/pixellib/ibmbits.h

https://github.com/skywind3000/pixellib/blob/master/pixellib/ibmbits.c

两个底层的文件，没有额外依赖。

**Comment by imkos** [comment]
1bit bitmap 在POS打印机 中很常见.
